export const REGISTER_SUCCESS = "REGISTER_SUCCESS" ;
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS" ;
export const LOGIN_FAIL = "LOGIN_FAIL" ;

export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS" ;
export const LOAD_USER_FAIL = "LOAD_USER_FAIL";

export const LOGOUT ="LOGOUT"; 

export const UPDATE_USER="UPDATE_USER"
export const UPDATE_FAIL="UPDATE_FAIL"

export const ADD_ANOUNNCE_SUCCESS="ADD_ANNOUNCE"
export const ADD_ANOUDNNCE_FAIL="ADD_ANOUDNNCE_FAIL"

export const LOAD_USER_ANNOUNCES_SUCCESS="LOAD_USER_ANNOUNCES_SUCCESS"
export const LOAD_USER_ANNOUNCES_FAIL = "LOAD_USER_ANNOUNCES_FAIL"

export const DELETE_ANNOUNCE_SUCCESS="DELETE_ANNOUNCE_SUCCESS"
export const DELETE_ANNOUNCE_FAIL="DELETE_ANNOUNCE_FAIL"

export const UPDATE_ANNOUNCE_SUCCESS = "UPDATE__ANNOUNCE_SUCCESS"
export const UPDATE_ANNOUNCE_FAIL="UPDATE__ANNOUNCE_FAIL"

export const GET_USERS_LIST_SUCCESS = "GET_USERS_LIST_SUCCESS"
export const GET_USERS_LIST_FAIL = "GET_USERS_LIST_FAIL"

export const TOGGLE_USER_SUCCESS ="TOGGLE_USER_SUCCESS"
export const TOGGLE_USER_FAIL ="TOGGLE_USER_FAIL"

export const GET_ANNOUNCE_LIST_SUCCESS  = "GET_ANNOUNCE_LIST_SUCCESS"
export const GET_ANNOUNCE_LIST_FAIL = "GET_ANNOUNCE_LIST_FAIL"

export const TOGGLE_APPROUVED_SUCCESS = "TOGGLE_APPROUVED_SUCCESS"
export const TOGGLE_APPROUVED_FAIL = "TOGGLE_APPROUVED_FAIL"

export const GET_APPROUVED_ANNOUNCE_LIST_SUCCESS = "GET_APPROUVED_ANNOUNCE_LIST_SUCCESS"
export const GET_APPROUVED_ANNOUNCE_LIST_FAIL = "GET_APPROUVED_ANNOUNCE_LIST_FAIL"

export const ADD_FAVORITE_SUCCESS ="ADD_FAVORITE_SUCCESS"
export const ADD_FAVORITE_FAIL = "ADD_FAVORITE_FAIL"

export const REMOVE_FROM_FAVORITE_SUCCESS = "REMOVE_FROM_FAVORITE_SUCCESS"
export const REMOVE_FROM_FAVORITE_FAIL = "REMOVE_FROM_FAVORITE_FAIL" 

export const LOAD_FAVORITE_LIST_SUCCESS ="LOAD_FAVORITE_LIST_SUCCESS" 
export const LOAD_FAVORITE_LIST_FAIL = "LOAD_FAVORITE_LIST_FAIL"

export const GET_USER_OF_ANNOUNCE_SUCCESS="GET_USER_OF_ANNOUNCE_SUCCESS"
export const GET_USER_OF_ANNOUNCE_FAIL="GET_USER_OF_ANNOUNCE_FAIL"

export const FILTER_ANNOUNCES_SUCCESS="FILTER_ANNOUNCES_SUCCESS"
export const FILTER_ANNOUNCES_FAIL="FILTER_ANNOUNCES_FAIL"

export const SEARCH_BY_TITLE_SUCCESS="SEARCH_BY_TITLE_SUCCESS"
export const SEARCH_BY_TITLE_FAIL="SEARCH_BY_TITLE_FAIL"

export const ADD_COMMENT_SUCCESS= "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAIL="ADD_COMMENT_FAIL"

export const LOAD_ANNOUNCE_SUCCESS="LOAD_ANNOUNCE_SUCCESS"
export const LOAD_ANNOUNCE_FAIL="LOAD_ANNOUNCE_FAIL"

export const DELETE_COMMENT_SUCCESS="DELETE_COMMENT_SUCCESS"
export const DELETE_COMMENT_FAIL="DELETE_COMMENT_FAIL"

export const UPDATE_COMMENT_SUCCESS="UPDATE_COMMENT_SUCCESS"
export const UPDATE_COMMENT_FAIL="UPDATE_COMMENT_FAIL" 

export const SEARCH_FOR_USERS_SUCCESS ="SEARCH_FOR_USERS_SUCCESS"
export const SEARCH_FOR_USERS_FAIL="SEARCH_FOR_USERS_FAIL"

export const FILTER_USERS_SUCCESS="FILTER_USERS_SUCCESS" 
export const FILTER_USERS_FAIL="FILTER_USERS_FAIL"

export const FILTER_ANNOUNCES_APPNOT_SUCCESS="FILTER_ANNOUNCES_APPNOT_SUCCESS" 
export const FILTER_ANNOUNCES_APPNOT_FAIL="FILTER_ANNOUNCES_APPNOT_FAIL" 

export const SEARCH_BY_TITLE_ADMIN_SUCCESS="SEARCH_BY_TITLE_ADMIN_SUCCESS"
export const SEARCH_BY_TITLE_ADMIN_FAIL="SEARCH_BY_TITLE_ADMIN_FAIL"